In [1]:
import numpy as np

In [3]:
mylist = [1, 2, 3]

In [5]:
mylist

[1, 2, 3]

In [7]:
myarray = np.array(mylist)

In [9]:
myarray

array([1, 2, 3])

In [11]:
type(myarray)

numpy.ndarray

In [13]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(1)

array([0.21370082])

In [27]:
np.random.rand(5, 6)

array([[0.74962942, 0.64716717, 0.763284  , 0.93148351, 0.17290279,
        0.11915631],
       [0.45234634, 0.73423551, 0.52846983, 0.71853684, 0.3116513 ,
        0.46378786],
       [0.64230806, 0.09160442, 0.440039  , 0.03644457, 0.0068465 ,
        0.78214458],
       [0.77061111, 0.40475065, 0.4652612 , 0.74217023, 0.74839275,
        0.22099303],
       [0.85733208, 0.03693474, 0.12848457, 0.34128936, 0.89278235,
        0.89509421]])

In [29]:
np.random.randn(10)

array([-0.12186478,  0.03701605, -1.05755006,  0.88148849, -0.49203358,
        0.04004362, -1.40736278, -1.149289  ,  0.07320098, -0.17511559])

In [31]:
np.random.randn(2, 3)

array([[-0.10581781,  1.67505476,  0.95959777],
       [-0.78998383,  0.55940259, -0.64245902]])

In [35]:
np.random.randint(0, 101, (5, 6))

array([[50, 93, 73, 39, 84, 51],
       [18, 49, 24, 46,  8, 46],
       [24, 87, 56, 29, 44, 46],
       [84, 15, 94, 45, 92, 95],
       [50,  8, 77, 50, 56, 51]], dtype=int32)

In [37]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [39]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [43]:
np.random.rand(5)

array([0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [45]:
arr = np.arange(0, 25)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
arr.reshape(5, 5) # only reshape fit with 25 elements

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
ranarr = np.random.randint(0, 101, 25) # Create an int random array of 25 elements which own the values in [0, 100]  

In [55]:
ranarr

array([21, 52,  1, 87, 29, 37,  1, 63, 59, 20, 32, 75, 57, 21, 88, 48, 90,
       58, 41, 91, 59, 79, 14, 61, 61], dtype=int32)

In [57]:
ranarr.max() # Find max value in the random array

np.int32(91)

In [59]:
ranarr.argmax() # Indicate the index of max value in the random array

np.int64(19)

In [61]:
ranarr.min()

np.int64(2)

In [63]:
ranarr.argmin()

np.int64(2)

In [67]:
ranarr.dtype

dtype('int32')

In [69]:
arr.shape

(25,)

In [77]:
arr = arr.reshape(5, 5)

In [79]:
arr.shape

(5, 5)