In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 25)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [7]:
arr[8]

np.int64(8)

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [11]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [13]:
arr[:5]

array([0, 1, 2, 3, 4])

In [15]:
arr[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
arr[:5] = 100

In [19]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [23]:
arr=np.arange(0, 25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
slice_of_arr = arr[:5]

In [29]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [31]:
slice_of_arr[:]=99

In [33]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [35]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr_copy = arr.copy()

In [39]:
arr_copy[:]=99

In [41]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99])

In [43]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7 , 8, 9]])

In [49]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr_2d.shape

(3, 3)

In [53]:
arr_2d[2]

array([7, 8, 9])

In [55]:
arr_2d[2][0]

np.int64(7)

In [57]:
arr_2d[2][0].shape

()

In [59]:
arr_2d[1, 1]

np.int64(5)

In [61]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
arr_2d[:2, 2:]

array([[3],
       [6]])

In [67]:
arr_2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [71]:
arr = np.arange(0, 25)

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [76]:
arr > 11

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [78]:
bool_ = arr>11 

In [80]:
bool_

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [86]:
arr[bool_]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [88]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])